# Dependencies
markdown:         redcarpet

# Permalinks
# permalink:        pretty

# Setup
title:            EarthSkyLab
tagline:          'An Open Model for A Deeply Connected Life-long Free to Learn Community. - Time is Now!'
description:      'An Open Model for A Deeply Connected Life-long Free to Learn Community. - Time is Now!'
url:              http://www.earthskylab.vision
facebook: 	https://www.facebook.com/EarthSkyLab
author:
  name:           'EarthSkyLab'
  url:            http://www.earthskylab.vision/

paginate:         5

# Custom vars
version:          1.0

github:
  repo:           https://github.com/vvorski/vvorski.github.io

excerpt_separator: <!-- more -->

collections:
  authors:
    output: true
